name: cs231n_HW
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0=mkl
  - brotli-python=1.0.9=py312h5da7b33_9
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.2.25=haa95532_0
  - contourpy=1.3.1=py312h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=3.0.11=py312h827c3e9_1
  - expat=2.6.4=h8ddb27b_0
  - fonttools=4.55.3=py312h827c3e9_0
  - freetype=2.12.1=ha860e81_0
  - future=1.0.0=py312haa95532_0
  - h5py=3.12.1=py312h535c9fb_1
  - hdf5=1.14.5=ha36df97_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - imageio=2.37.0=py312haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jpeg=9e=h827c3e9_3
  - kiwisolver=1.4.8=py312h5da7b33_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.16=hb4a4139_0
  - lerc=4.0.0=h5da7b33_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h70ee33d_0
  - libtiff=4.5.1=h44ae7cf_1
  - libwebp-base=1.3.2=h3d04722_1
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib=3.10.0=py312haa95532_0
  - matplotlib-base=3.10.0=py312he19b0ae_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h827c3e9_2
  - mkl_fft=1.3.11=py312h827c3e9_0
  - mkl_random=1.2.8=py312h0158946_0
  - numpy-base=2.0.1=py312h4dde369_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.16=h3f729d1_0
  - packaging=24.2=py312haa95532_0
  - pip=25.0=py312haa95532_0
  - pyparsing=3.2.0=py312haa95532_0
  - pyqt=6.7.1=py312h5da7b33_0
  - pyqt6-sip=13.9.1=py312h827c3e9_0
  - python=3.12.9=h14ffc60_0
  - python-dateutil=2.9.0post0=py312haa95532_2
  - qtbase=6.7.2=h0804d20_1
  - qtdeclarative=6.7.2=h5da7b33_0
  - qtsvg=6.7.2=hf2fb9eb_0
  - qttools=6.7.2=h0de5f00_0
  - qtwebchannel=6.7.2=h5da7b33_0
  - qtwebsockets=6.7.2=h5da7b33_0
  - scipy=1.15.1=py312hbb039d4_0
  - setuptools=75.8.0=py312haa95532_0
  - sip=6.10.0=py312h5da7b33_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.4.2=py312h827c3e9_0
  - unicodedata2=15.1.0=py312h827c3e9_1
  - vc=14.42=haa95532_4
  - vs2015_runtime=14.42.34433=he0abc0d_4
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - attrs==25.3.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - colorama==0.4.6
      - comet-ml==3.49.10
      - configobj==5.0.9
      - dulwich==0.22.8
      - et-xmlfile==2.0.0
      - everett==3.1.0
      - filelock==3.13.1
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - idna==3.10
      - jinja2==3.1.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - lazy-loader==0.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.1.2
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - pandas==2.2.3
      - pillow==11.0.0
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pygments==2.19.1
      - python-box==6.1.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==14.0.0
      - rpds-py==0.25.1
      - scikit-image==0.25.2
      - semantic-version==2.10.0
      - sentry-sdk==2.29.1
      - simplejson==3.20.1
      - smmap==5.0.2
      - sympy==1.13.1
      - tifffile==2025.10.4
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchsummary==1.5.1
      - torchvision==0.21.0+cu124
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - ultralytics==8.3.144
      - ultralytics-thop==2.0.14
      - urllib3==2.4.0
      - wrapt==1.17.2
      - wurlitzer==3.1.1
prefix: D:\Users\xdche\anaconda3\envs\cs231n_HW
